layout_spectrum: 0.7396712894551456
typography_spectrum: 0.3803302685264498
color:
  brandColors:
    - '#12150D'
    - '#3A2F2F'
    - '#3C5432'
    - '#4A8159'
    - '#70666F'
  brandStrength: 0.6556808038149029
  lightness: 0.8375916187651455
  saturation: 0.8460384008940309
  rhythmicContrast: 0.03521412471309304
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Gnör Gnörsson
  url: gnor.co
  email: i@gnor.co
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/519e10ed-4918-453a-a01e-d87eca1d8618.png
name: "I, \_G N Ö R"
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: '@gnor_gnorsson'
    id: 66a6b0e2-47d0-4b12-9db7-1158d7786864
    type: content
  - name: Contact
    url: 'http://shemk.ai/contact'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/850f8c52-30ad-4c09-b84b-8da81186ed04.png
title: 'When I become the Internet, I am going to space.'
description: Sideshoot of Gnör Gnörsson
purpose: []
