typography_spectrum: 0.5254239281639457
color:
  brandColors:
    - '#000000'
    - '#EAEAEA'
    - '#2D3200'
    - '#967F00'
    - '#005B4F'
  brandStrength: 0.06599193601869047
  lightness: 0.6693748096004128
  saturation: 0.8053774703294039
  rhythmicContrast: 0.07999362563714385
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5400783740915358
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Gnör Gnörsson
  url: gnor.co
  email: i@gnor.co
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/519e10ed-4918-453a-a01e-d87eca1d8618.png
name: "I, \_G N Ö R"
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: '@gnor_gnorsson'
    id: 66a6b0e2-47d0-4b12-9db7-1158d7786864
    type: content
  - name: Contact
    url: 'http://shemk.ai/contact'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/850f8c52-30ad-4c09-b84b-8da81186ed04.png
title: 'When I become the Internet, I am going to space.'
description: Sideshoot of Gnör Gnörsson
purpose: []
